script: 'ci/travis.rb'
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - rbx-2
  - jruby
env:
  - "GEM=railties"
  - "GEM=ap,am,amo,as"
  - "GEM=ar:mysql2"
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
bundler_args: --path vendor/bundle --without test
services:
  - memcached
